services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/dev"
      # dummy secret
      SECRET_KEY_BASE: "09wFngCQBx823enH6DyF5idFNJj1ggbyD+ebyj2bicPIsppr5QekFGnvfivY+5IU" 
    ports:
      - "4000:4000"

  # frontend:
  #   build: .
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: "postgres://postgres:postgres@db/dev"
  #     SECRET_KEY_BASE: "09wFngCQBx823enH6DyF5idFNJj1ggbyD+ebyj2bicPIsppr5QekFGnvfivY+5IU" 
  #   ports:
  #     - "4000:4000"
